build-ssa-git-yaml-file-version-bumper:
  tags:
    - piximos
  stage:
    build-sa-bash
  variables:
    IMAGE_NAME: "scriptedatom/git-yaml-file-version-bumper"
    DOCKER_IMAGE_PATH: "./sa-gitters/git-yaml-file-version-bumper-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-gitters/git-yaml-file-version-bumper-atom/."
  script:
    - ./ci-cd/scripts/build-public-image.sh
  needs:
    - build-sa-gitter

