include:
  - local: /ci-cd/comwork-templates/.base-images-builder-template.yml
  - local: /ci-cd/comwork-templates/.scripted-api-atoms-builder-template.yml
  - local: /ci-cd/comwork-templates/.scripted-task-atoms-builder-template.yml

stages:
  - build-bases
  - build-scripted-api-atoms
  - build-scripted-task-atoms
  - clean-dev-data

variables:
  VERSION: "0.0.1"

clean-images:
  tags:
    - soyoustart1
  only:
    - /^(master)$/
  stage:
    clean-dev-data
  script:
    - ./ci-cd/scripts/clean-image.sh
  needs:
    - build-scripted-api-atoms-base
    - build-scripted-task-atoms-base
    - build-sta-s3-file-sync
    - build-sta-uptime-tracker
    - build-saa-qr-code-s3
    - build-saa-qr-code-fs
    - build-saa-otp-maker
    - build-saa-s3-unzipper
  artifacts:
    paths:
      - ./build-artifacts/output.txt
      - ./build-artifacts/build-log.txt
    expire_in: 7 days
