include:
  - local: /ci-cd/comwork-templates/.base-images-builder-template.yml
  - local: /ci-cd/comwork-templates/.scripted-api-atoms-builder-template.yml
  - local: /ci-cd/comwork-templates/.scripted-task-atoms-builder-template.yml
  # Dev environment templates
  - local: /ci-cd/comwork-templates/dev-templates/.base-images-builder-template.yml
  - local: /ci-cd/comwork-templates/dev-templates/.scripted-api-atoms-builder-template.yml
  - local: /ci-cd/comwork-templates/dev-templates/.scripted-task-atoms-builder-template.yml
  # Mirroring templates
  - local: /ci-cd/comwork-templates/mirroring-templates/.mirror-bases-template.yml
  - local: /ci-cd/comwork-templates/mirroring-templates/.mirror-scripted-api-atoms-template.yml
  - local: /ci-cd/comwork-templates/mirroring-templates/.mirror-scripted-task-atoms-template.yml

stages:
  - build-bases
  - build-scripted-api-atoms
  - build-scripted-task-atoms
  - mirror-bases
  - mirror-scripted-api-atoms
  - mirror-scripted-task-atoms
  - clean-dev-data

variables:
  VERSION: "0.0.1"

build-sta-uptime-tracker:
  tags:
    - soyoustart1
  only:
    - /^(master)$/
  stage:
    clean-dev-data
  script:
    - ./ci-cd/scripts/clean-image.sh
  dependencies:
    - build-scripted-api-atoms-base
    - build-scripted-task-atoms-base
    - build-sta-s3-file-sync
    - build-sta-uptime-tracker
    - build-saa-qr-code-s3
    - build-saa-qr-code-fs
    - build-saa-otp-maker
    - docker-mirror-scripted-api-atoms-base
    - docker-mirror-scripted-task-atoms-base
    - docker-mirror-saa-qr-code-s3
    - docker-mirror-saa-qr-code-fs
    - docker-mirror-saa-otp-maker
    - docker-mirror-saa-s3-unzipper
    - docker-mirror-sta-s3-file-sync
    - docker-mirror-sta-uptime-tracker
  artifacts:
    paths:
      - ./output.txt
    expire_in: 7 days
