include:
  - local: /ci-cd/comwork-templates/.base-images-builder-template.yml
  - local: /ci-cd/comwork-templates/.scripted-api-atoms-builder-template.yml
  - local: /ci-cd/comwork-templates/.scripted-task-atoms-builder-template.yml

stages:
  - pre-flight
  - build-bases
  - build-scripted-api-atoms
  - build-scripted-task-atoms
  - clean-dev-data

variables:
  VERSION: "0.0.1"

clean-images:
  tags:
    - piximos
  stage:
    clean-dev-data
  script:
    - ./ci-cd/scripts/clean-image.sh

validate-branch-name:
  tags:
    - piximos
  allow_failure: false
  stage:
    pre-flight
  script:
    - ./ci-cd/scripts/validate-commit.sh
