include:
  - local: /ci-cd/ci-templates/.git-sync-template.yml
  # Scripted API Atom Version Variables
  - local: /scripted-api-atoms/scripted-api-atoms-base/.gitlab-ci.yml
  - local: /scripted-api-atoms/otp-maker-atom/.gitlab-ci.yml
  - local: /scripted-api-atoms/qr-code-fs-atom/.gitlab-ci.yml
  - local: /scripted-api-atoms/qr-code-s3-atom/.gitlab-ci.yml
  - local: /scripted-api-atoms/s3-file-unzipper-atom/.gitlab-ci.yml
  - local: /scripted-api-atoms/thumbnail-generator-s3-atom/.gitlab-ci.yml
  # Scripted Simple Atom Version Variables
  - local: /scripted-simple-atoms/scripted-simple-atoms-base/.gitlab-ci.yml
  - local: /scripted-simple-atoms/git-mirror-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/git-tagger-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/nexus-image-cleaner-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/harbor-image-cleaner-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/pipeline-slacker-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/pipeline-discorder-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/s3-file-backup-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/uptime-slacker-atom/.gitlab-ci.yml
  # Scripted Task Atom Version Variables
  - local: /scripted-task-atoms/scripted-task-atoms-base/.gitlab-ci.yml
  - local: /scripted-task-atoms/s3-file-sync-atom/.gitlab-ci.yml

stages:
  - pre-flight
  - build-bases
  - build-scripted-simple-atoms
  - build-scripted-api-atoms
  - build-scripted-task-atoms
  - broadcast
  - git-tagger
  - git-sync

before_script:
  - echo "$DOCKER_REGISTRY_TOKEN" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin

validate-branch-name:
  tags:
    - piximos
  allow_failure: false
  stage:
    pre-flight
  script:
    - ./ci-cd/scripts/validate-commit.sh

variables:
  # Scripted Api Atom Version Variables
  saa_base_version: "1.0"
  saa_qr_code_s3_version: "1.0"
  saa_qr_code_fs_version: "1.0"
  saa_otp_maker_version: "1.0"
  saa_s3_file_unzipper_version: "1.0"
  saa_thumbnail_generator_s3_version: "1.0"
  # Scripted Task Atom Version Variables
  sta_base_version: "1.0"
  sta_s3_file_sync_version: "1.0"
  # Scripted Simple Atom Version Variables
  ssa_base_version: "1.0"
  ssa_s3_file_backup_version: "1.0"
  ssa_git_tagger_version: "1.0"
  ssa_git_mirror_version: "1.0"
  ssa_pipeline_slacker_version: "1.0"
  ssa_pipeline_discorder_version: "1.0"
  ssa_pipeline_harbor_image_cleaner_version: "1.0"
  ssa_pipeline_nexus_image_cleaner_version: "1.0"
  ssa_pipeline_uptime_slacker_version: "1.0"
