include:
  - local: /ci-cd/ci-templates/.base-images-builder-template.yml
  - local: /ci-cd/ci-templates/.scripted-api-atoms-builder-template.yml
  - local: /ci-cd/ci-templates/.scripted-simple-atoms-builder-template.yml
  - local: /ci-cd/ci-templates/.scripted-task-atoms-builder-template.yml
  - local: /ci-cd/ci-templates/arm/.base-images-builder-template.yml
  - local: /ci-cd/ci-templates/arm/.scripted-api-atoms-builder-template.yml
  - local: /ci-cd/ci-templates/arm/.scripted-simple-atoms-builder-template.yml
  - local: /ci-cd/ci-templates/arm/.scripted-task-atoms-builder-template.yml
  - local: /ci-cd/ci-templates/.git-sync-template.yml
  - local: /ci-cd/ci-templates/.post-flight-template.yml
  - local: /ci-cd/ci-templates/.slackers-template.yml

stages:
  - pre-flight
  - git-tagger
  - build-bases
  - build-arm-bases
  - build-scripted-simple-atoms
  - build-scripted-api-atoms
  - build-scripted-task-atoms
  - git-sync
  - broadcast
  - post-flight

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  - echo "$DOCKER_REGISTRY_TOKEN" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin
