include:
  - local: /ci-cd/ci-templates/.base-images-builder-template.yml
  - local: /ci-cd/ci-templates/.scripted-api-atoms-builder-template.yml
  - local: /ci-cd/ci-templates/.scripted-simple-atoms-builder-template.yml
  - local: /ci-cd/ci-templates/.scripted-task-atoms-builder-template.yml
  - local: /ci-cd/ci-templates/.git-sync-template.yml
  - local: /scripted-simple-atoms/nexus-image-cleaner-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/harbor-image-cleaner-atom/.gitlab-ci.yml

stages:
  - pre-flight
  - git-tagger
  - build-bases
  - build-arm-bases
  - build-scripted-simple-atoms
  - build-scripted-api-atoms
  - build-scripted-task-atoms
  - git-sync
  - broadcast
  - post-flight

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  - echo "$DOCKER_REGISTRY_TOKEN" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin

validate-branch-name:
  tags:
    - piximos
  allow_failure: false
  stage:
    pre-flight
  script:
    - ./ci-cd/scripts/validate-commit.sh

variables:
  # Scripted Api Atom Version Variables
  saa_base_version: "1.0"
  saa_qr_code_s3_version: "1.0"
  saa_qr_code_fs_version: "1.0"
  saa_otp_maker_version: "1.0"
  saa_s3_unzipper_version: "1.0"
  saa_thumbnail_generator_s3_version: "1.0"
  # Scripted Task Atom Version Variables
  sta_base_version: "1.0"
  sta_s3_file_sync_version: "1.0"
  sta_uptime_tracker_version: "1.0"
  # Scripted Simple Atom Version Variables
  ssa_base_version: "1.0"
  ssa_s3_file_backup_version: "1.0"
  ssa_git_tagger_version: "1.0"
  ssa_git_mirror_version: "1.0"
  ssa_pipeline_slacker_version: "1.0"
  ssa_pipeline_harbor_image_cleaner_version: "1.0"
  ssa_pipeline_nexus_image_cleaner_version: "1.0"