include:
  - local: /ci-cd/ci-templates/.base-images-builder-template.yml
  - local: /ci-cd/ci-templates/.scripted-api-atoms-builder-template.yml
  # Dev environment templates
  - local: /ci-cd/ci-templates/dev-templates/.base-images-builder-template.yml
  - local: /ci-cd/ci-templates/dev-templates/.scripted-api-atoms-builder-template.yml
  # Mirroring templates
  - local: /ci-cd/ci-templates/mirroring-templates/.mirror-bases-template.yml
  - local: /ci-cd/ci-templates/mirroring-templates/.mirror-scripted-api-atoms-template.yml

stages:
  - build-bases
  - build-scripted-api-atoms
  - mirror-bases
  - mirror-scripted-api-atoms
  - clean-dev-data

variables:
  VERSION: "0.0.1"