include:
  - local: /ci-cd/ci-templates/.git-sync-template.yml
  # Scripted API Atom Version Variables
  - local: /scripted-api-atoms/scripted-api-atoms-base/.gitlab-ci.yml
  - local: /scripted-api-atoms/otp-maker-atom/.gitlab-ci.yml
  - local: /scripted-api-atoms/qr-code-fs-atom/.gitlab-ci.yml
  - local: /scripted-api-atoms/qr-code-s3-atom/.gitlab-ci.yml
  - local: /scripted-api-atoms/s3-file-unzipper-atom/.gitlab-ci.yml
  - local: /scripted-api-atoms/thumbnail-generator-s3-atom/.gitlab-ci.yml
  # Scripted Simple Atom Version Variables
  - local: /scripted-simple-atoms/scripted-simple-atoms-base/.gitlab-ci.yml
  - local: /scripted-simple-atoms/git-mirror-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/git-tagger-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/git-yaml-file-version-bumper-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/nexus-image-cleaner-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/harbor-image-cleaner-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/pipeline-slacker-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/pipeline-discorder-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/s3-file-backup-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/uptime-slacker-atom/.gitlab-ci.yml
  - local: /scripted-simple-atoms/uptime-discorder-atom/.gitlab-ci.yml
  # Scripted Task Atom Version Variables
  - local: /scripted-task-atoms/scripted-task-atoms-base/.gitlab-ci.yml
  - local: /scripted-task-atoms/s3-file-sync-atom/.gitlab-ci.yml

stages:
  - pre-flight
  - build-bases
  - build-scripted-simple-atoms
  - build-scripted-api-atoms
  - build-scripted-task-atoms
  - slack-broadcast
  - discord-broadcast
  - cleaner
  - git-sync

before_script:
  - echo "$DOCKER_REGISTRY_TOKEN" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin

validate-branch-name:
  tags:
    - piximos
  allow_failure: false
  stage:
    pre-flight
  script:
    - ./ci-cd/scripts/validate-commit.sh

variables:
  # Scripted Api Atom Version Variables
  saa_base_version: "1.0"
  # Scripted Task Atom Version Variables
  sta_base_version: "1.0"
  # Scripted Simple Atom Version Variables
  ssa_base_version: "1.1"
