include:
  - local: /ci-cd/ci-templates/.git-sync-template.yml
  # Scripted Atom Bases
  - local: /sa-bases/sa-bash.gitlab-ci.yml
  - local: /sa-bases/sa-gitter.gitlab-ci.yml
  - local: /sa-bases/sa-python.gitlab-ci.yml
  - local: /sa-bases/sa-fastapi.gitlab-ci.yml
  # Scripted API Atoms
  #   SA FastApi
  - local: /sa-fastapi/otp-maker-atom/.gitlab-ci.yml
  - local: /sa-fastapi/qr-code-fs-atom/.gitlab-ci.yml
  - local: /sa-fastapi/qr-code-s3-atom/.gitlab-ci.yml
  - local: /sa-fastapi/s3-file-unzipper-atom/.gitlab-ci.yml
  - local: /sa-fastapi/thumbnail-generator-s3-atom/.gitlab-ci.yml
  - local: /sa-fastapi/redis-publisher-atom/.gitlab-ci.yml
  # Scripted Simple Atoms
  #   SA Gitters
  - local: /sa-gitters/git-mirror-atom/.gitlab-ci.yml
  - local: /sa-gitters/git-tagger-atom/.gitlab-ci.yml
  - local: /sa-gitters/git-yaml-file-version-bumper-atom/.gitlab-ci.yml
  #   SA Basics
  - local: /sa-bash/nexus-image-cleaner-atom/.gitlab-ci.yml
  - local: /sa-bash/harbor-image-cleaner-atom/.gitlab-ci.yml
  - local: /sa-bash/docker-hub-image-cleaner-atom/.gitlab-ci.yml
  - local: /sa-bash/pipeline-slacker-atom/.gitlab-ci.yml
  - local: /sa-bash/pipeline-discorder-atom/.gitlab-ci.yml
  - local: /sa-bash/uptime-slacker-atom/.gitlab-ci.yml
  - local: /sa-bash/uptime-discorder-atom/.gitlab-ci.yml
  - local: /sa-bash/tag-pill-svg-generator-atom/.gitlab-ci.yml
  #   SA S3
  - local: /sa-s3/s3-file-backup-atom/.gitlab-ci.yml
  #   SA Python
  - local: /sa-python/redis-subscriber-atom/.gitlab-ci.yml

stages:
  - pre-flight
  - build-bases
  - build-sa-bash
  - build-sa-fastapi
  - build-sa-python
  - build-sa-s3
  - post-flight
  - git-sync

before_script:
  - echo "$DOCKER_REGISTRY_TOKEN" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin

validate-branch-name:
  tags:
    - piximos
  allow_failure: false
  environment:
    name: review/$CI_COMMIT_REF_NAME
    on_stop: clear-docker-tags
  stage:
    pre-flight
  script:
    - ./ci-cd/scripts/validate-commit.sh

clear-docker-tags:
  tags:
    - piximos
  allow_failure: false
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  stage:
    pre-flight
  script:
    - ./ci-cd/scripts/delete-tags.sh