include:
  - local: /ci-cd/ci-templates/.base-images-builder-template.yml
  - local: /ci-cd/ci-templates/.scripted-api-atoms-builder-template.yml
  - local: /ci-cd/ci-templates/.scripted-simple-atoms-builder-template.yml
  - local: /ci-cd/ci-templates/.scripted-task-atoms-builder-template.yml
  - local: /ci-cd/ci-templates/.git-sync-template.yml
  - local: /ci-cd/ci-templates/.git-tagger-template.yml

stages:
  - pre-flight
  - git-tagger
  - build-bases
  - build-arm-bases
  - build-scripted-simple-atoms
  - build-scripted-api-atoms
  - build-scripted-task-atoms
  - git-sync
  - clean-dev-data

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  - echo "$DOCKER_REGISTRY_TOKEN" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin

variables:
  BUILD_FOR_PRIVATE_REGISTRY: "true"
  MIRROR: "false"

clean-images:
  tags:
    - piximos
  stage:
    clean-dev-data
  script:
    - ./ci-cd/scripts/clean-image.sh
  dependencies:
    - build-scripted-api-atoms-base
    - build-scripted-task-atoms-base
    - build-sta-s3-file-sync
    - build-sta-uptime-tracker
    - build-saa-qr-code-s3
    - build-saa-qr-code-fs
    - build-saa-otp-maker
    - build-saa-s3-unzipper

validate-branch-name:
  tags:
    - piximos
  allow_failure: false
  stage:
    pre-flight
  script:
    - ./ci-cd/scripts/validate-commit.sh
