include:
  - local: /ci-cd/ci-templates/.mirror-template.yml
  - local: /ci-cd/ci-templates/.base-images-builder-template.yml
  - local: /ci-cd/ci-templates/.scripted-api-atoms-builder-template.yml
  - local: /ci-cd/ci-templates/dev-templates/.base-images-builder-template.yml
  - local: /ci-cd/ci-templates/dev-templates/.scripted-api-atoms-builder-template.yml

stages:
  - build-bases
  - build-scripted-api-atoms
  - mirror-bases
  - clean-dev-data

variables:
  VERSION: "0.0.1"