build-arm-scripted-api-atoms-base:
  tags:
    - piximos-arm
  stage:
    build-arm-bases
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(develop.*)|(dev.*)$/
      changes:
        - scripted-api-atoms/scripted-api-atoms-base/*
        - scripted-api-atoms/qr-code-s3-atom/*
        - scripted-api-atoms/qr-code-fs-atom/*
        - scripted-api-atoms/otp-maker-atom/*
        - scripted-api-atoms/s3-file-unzipper-atom/*
        - scripted-api-atoms/thumbnail-generator-s3-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "false"
        PUBLIC_IMAGE_NAME: "piximos/scripted-api-atoms-base"
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms-base"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/scripted-api-atoms-base/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/scripted-api-atoms-base/."
    IMG_COMPLEMENTARY_TAG: "-arm"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./ci-cd/scripts/build-image.sh
  needs:
    - validate-branch-name

build-arm-scripted-task-atoms-base:
  tags:
    - piximos-arm
  stage:
    build-arm-bases
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(develop.*)|(dev.*)$/
      changes:
        - scripted-task-atoms/scripted-task-atoms-base/*
        - scripted-task-atoms/s3-file-sync-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "false"
        PUBLIC_IMAGE_NAME: "piximos/scripted-task-atoms-base"
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-task-atoms-base"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-task-atoms/scripted-task-atoms-base/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-task-atoms/scripted-task-atoms-base/."
    IMG_COMPLEMENTARY_TAG: "-arm"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./ci-cd/scripts/build-image.sh
  needs:
    - validate-branch-name

build-arm-scripted-simple-atoms-base:
  tags:
    - piximos-arm
  stage:
    build-arm-bases
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(develop.*)|(dev.*)$/
      changes:
        - scripted-simple-atoms/scripted-simple-atoms-base/*
        - scripted-simple-atoms/s3-file-backup-atom/*
        - scripted-simple-atoms/git-tagger-atom/*
        - scripted-simple-atoms/git-mirror-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "false"
        PUBLIC_IMAGE_NAME: "piximos/scripted-simple-atoms-base"
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-simple-atoms-base"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-simple-atoms/scripted-simple-atoms-base/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-simple-atoms/scripted-simple-atoms-base/."
    IMG_COMPLEMENTARY_TAG: "-arm"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./ci-cd/scripts/build-image.sh
  needs:
    - validate-branch-name