build-ssa-git-mirror:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
    - if: $CI_COMMIT_REF_NAME =~ /^(ci|sa|ssa|saa|sta)\-?(\-.*)?$/
      variables:
        SA_BETA_BUILD: "true"
  stage:
    build-sa-bash
  variables:
    IMAGE_NAME: "scriptedatom/git-mirror"
    DOCKER_IMAGE_PATH: "./sa-gitters/git-mirror-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-gitters/git-mirror-atom/."
  script:
    - ./ci-cd/scripts/build-public-image.sh
  needs:
    - build-sa-gitter

