docker-mirror-scripted-api-atoms-base:
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  only:
    - /^(master.*)$/
  stage:
    mirror-bases
  needs:
    - job: build-scripted-api-atoms-base
  variables:
    IMAGE_NAME: "piximos/scripted-api-atoms-base"
    IMG_TAG: "latest"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/scripted-api-atoms-base/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/scripted-api-atoms-base/."
  script:
    - echo "$DOCKER_REGISTRY_TOKEN" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin
    - ./ci-cd/scripts/build-public-image.sh

docker-mirror-scripted-task-atoms-base:
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  only:
    - /^(master.*)$/
  stage:
    mirror-bases
  needs:
    - job: build-scripted-task-atoms-base
  variables:
    IMAGE_NAME: "piximos/scripted-api-atoms-base"
    IMG_TAG: "latest"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/scripted-api-atoms-base/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/scripted-api-atoms-base/."
  script:
    - echo "$DOCKER_REGISTRY_TOKEN" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin
    - ./ci-cd/scripts/build-public-image.sh
