build-ssa-git-tagger:
  tags:
    - piximos
  stage:
    build-sa-bash
  variables:
    IMAGE_NAME: "scriptedatom/git-tagger"
    DOCKER_IMAGE_PATH: "./sa-gitters/git-tagger-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-gitters/git-tagger-atom/."
  script:
    - ./ci-cd/scripts/build-public-image.sh
  needs:
    - build-sa-gitter

