build-saa-qr-code-s3:
  tags:
    - piximos
  stage:
    build-sa-fastapi
  variables:
    IMAGE_NAME: "scriptedatom/qr-code-generator-s3"
    DOCKER_IMAGE_PATH: "./sa-fastapi/qr-code-s3-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-fastapi/qr-code-s3-atom/."
  script:
    - ./ci-cd/scripts/build-public-image.sh
  needs:
    - build-sa-fastapi

