build-saa-qr-code-s3:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      when: on_success
    - if: $CI_COMMIT_REF_NAME =~ /^(ci|sa|ssa|saa|sta)\-?(\-.*)?$/
      when: on_success
      variables:
        SA_BETA_BUILD: "true"
  stage:
    build-sa-fastapi
  variables:
    IMAGE_NAME: "scriptedatom/qr-code-generator-s3"
    DOCKER_IMAGE_PATH: "./sa-fastapi/qr-code-s3-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-fastapi/qr-code-s3-atom/."
  script:
    - ./ci-cd/scripts/build-public-image.sh
  needs:
    - build-sa-fastapi

saa-qr-code-s3-post-flight:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(ci|sa|ssa|saa|sta)\-?(\-.*)?$/
      when: on_success
      variables:
        SA_BETA_BUILD: "true"
        SUCCESS: "true"
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      when: on_success
      variables:
        SUCCESS: "true"
    - if: $CI_COMMIT_REF_NAME =~ /^(ci|sa|ssa|saa|sta)\-?(\-.*)?$/
      when: on_failure
      variables:
        SA_BETA_BUILD: "true"
        SUCCESS: "false"
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      when: on_failure
      variables:
        SUCCESS: "false"
  variables:
    IMAGE: "scriptedatom/qr-code-generator-s3"
    TAGS: "latest"
  stage:
    post-flight
  needs:
    - build-saa-qr-code-s3
  script:
    - ./ci-cd/scripts/pipeline-after-build.sh
