build-sa-gitter:
  tags:
    - piximos
  stage:
    build-bases
  variables:
    IMAGE_NAME: "scriptedatom/sa-gitter"
    DOCKER_IMAGE_PATH: "./sa-bases/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-bases/."
    SA_BASE_IMAGE: "alpine"
    SA_TARGET: "sa_gitter"
  script:
    - ./ci-cd/scripts/build-runtime-image.sh
  needs:
    - validate-branch-name

