build-sa-python:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
    - if: $CI_COMMIT_REF_NAME =~ /^(ci|sa|ssa|saa|sta)\-?(\-.*)?$/
      variables:
        SA_BETA_BUILD: "true"
  stage:
    build-bases
  variables:
    IMAGE_NAME: "scriptedatom/sa-python"
    DOCKER_IMAGE_PATH: "./sa-bases/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-bases/."
    SA_BASE_IMAGE: "python:alpine"
    SA_TARGET: "sa_python"
  script:
    - ./ci-cd/scripts/build-runtime-image.sh
  needs:
    - validate-branch-name

