build-sa-s3:
  tags:
    - piximos
  stage:
    build-bases
  variables:
    IMAGE_NAME: "scriptedatom/sa-s3"
    DOCKER_IMAGE_PATH: "./sa-bases/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-bases/."
    SA_BASE_IMAGE: "alpine"
    SA_TARGET: "sa_s3"
  script:
    - ./ci-cd/scripts/build-runtime-image.sh
  needs:
    - validate-branch-name

