build-scripted-api-atoms-base:
  tags:
    - piximos
  stage:
    build-bases
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(develop.*)|(dev.*)$/
      changes:
        - scripted-api-atoms/*
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      variables:
        PUBLIC_IMAGE_NAME: "piximos/scripted-api-atoms-base"
      changes:
        - scripted-api-atoms/*
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms-base"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/scripted-api-atoms-base/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/scripted-api-atoms-base/."
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./ci-cd/scripts/build-image.sh

build-scripted-task-atoms-base:
  tags:
    - piximos
  stage:
    build-bases
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(develop.*)|(dev.*)$/
      changes:
        - scripted-task-atoms/*
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      variables:
        PUBLIC_IMAGE_NAME: "piximos/scripted-task-atoms-base"
      changes:
        - scripted-task-atoms/*
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-task-atoms-base"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-task-atoms/scripted-task-atoms-base/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-task-atoms/scripted-task-atoms-base/."
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./ci-cd/scripts/build-image.sh