build-scripted-api-atoms-base:
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  only:
    - /^(master)$/
  stage:
    build-bases
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms-base"
    IMG_TAG: "latest"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/scripted-api-atoms-base/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/scripted-api-atoms-base/."
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - ./ci-cd/scripts/build-image.sh

build-scripted-task-atoms-base:
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  only:
    - /^(master)$/
  stage:
    build-bases
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-task-atoms-base"
    IMG_TAG: "latest"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-task-atoms/scripted-task-atoms-base/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-task-atoms/scripted-task-atoms-base/."
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - ./ci-cd/scripts/build-image.sh