mirror-to-gitlab-com:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(master)|((minor|major)\-release)$/
      variables:
        CURRENT_REPO_URI: "gitlab.comwork.io/ydhraief/scripted-atoms.git"
        CURRENT_REPO_USER: ${COMWORK_REPO_USER}
        CURRENT_REPO_TOKEN: ${COMWORK_REPO_TOKEN}
        REMOTE_REPO_URI: "gitlab.com/piximos/scripted-atoms.git"
        REMOTE_REPO_USER: ${GITLAB_REPO_USER}
        REMOTE_REPO_TOKEN: ${GITLAB_REPO_TOKEN}
  stage:
    git-sync
  script:
    - ./ci-cd/scripts/mirror-repo.sh

mirror-to-github-com:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(master)|((minor|major)\-release)$/
      variables:
        CURRENT_REPO_URI: "gitlab.comwork.io/ydhraief/scripted-atoms.git"
        CURRENT_REPO_USER: ${COMWORK_REPO_USER}
        CURRENT_REPO_TOKEN: ${COMWORK_REPO_TOKEN}
        REMOTE_REPO_URI: "github.com/piximos/scripted-atoms.git"
        REMOTE_REPO_USER: ${GITHUB_REPO_USER}
        REMOTE_REPO_TOKEN: ${GITHUB_REPO_TOKEN}
  stage:
    git-sync
  script:
    - ./ci-cd/scripts/mirror-repo.sh

bump-tags:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^minor\-release$/
      variables:
        BUMP_TYPE: "minor"
    - if: $CI_COMMIT_REF_NAME =~ /^major\-release$/
      variables:
        BUMP_TYPE: "major"
  stage:
    git-tagger
  variables:
    REPO_URI: "gitlab.comwork.io/ydhraief/scripted-atoms.git"
    REPO_USER: ${COMWORK_REPO_USER}
    REPO_TOKEN: ${COMWORK_REPO_TOKEN}
  script:
    - ./ci-cd/scripts/bump-repo-tag.sh
  needs:
    - validate-branch-name
