bump-tags:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      variables:
        BUMP_TYPE: "minor"
    - if: $CI_COMMIT_REF_NAME =~ /^(stable\-release)$/
      variables:
        BUMP_TYPE: "major"
  stage:
    git-tagger
  variables:
    REPO_URI: "gitlab.comwork.io/ydhraief/scripted-atoms.git"
    REPO_USER: ${COMWORK_REPO_USER}
    REPO_TOKEN: ${COMWORK_REPO_TOKEN}
  script:
    - ./ci-cd/scripts/bump-repo-tag.sh
  needs:
    - validate-branch-name
