build-sta-s3-file-sync:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      variables:
        SA_BASE_VERSION: ${sta_base_version}
        IMAGE_VERSION: ${sta_s3_file_sync_version}
  stage:
    build-scripted-task-atoms
  variables:
    IMAGE_NAME: "scriptedatom/sta-s3-file-sync"
    DOCKER_IMAGE_PATH: "./scripted-task-atoms/s3-file-sync-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-task-atoms/s3-file-sync-atom/."
  needs:
    - build-sta-base
  script:
    - ./ci-cd/scripts/build-public-image.sh

build-sta-uptime-tracker:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      variables:
        SA_BASE_VERSION: ${sta_base_version}
        IMAGE_VERSION: ${sta_uptime_tracker_version}
  stage:
    build-scripted-task-atoms
  variables:
    IMAGE_NAME: "scriptedatom/sta-uptime-tracker"
    DOCKER_IMAGE_PATH: "./scripted-task-atoms/uptime-tracker-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-task-atoms/uptime-tracker-atom/."
  needs:
    - build-sta-base
  script:
    - ./ci-cd/scripts/build-public-image.sh

