build-saa-qr-code-s3:
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  only:
    - /^(master.*)$/
  stage:
    build-scripted-api-atoms
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/qr-code-generator-s3"
    IMG_TAG: "latest"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/qr-code-s3-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/qr-code-s3-atom/."
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - ./ci-cd/ci/build-image.sh

build-saa-qr-code-fs:
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  only:
    - /^(master.*)$/
  stage:
    build-scripted-api-atoms
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/qr-code-generator-fs"
    IMG_TAG: "latest"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/qr-code-fs-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/qr-code-fs-atom/."
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - ./ci-cd/ci/build-image.sh

build-saa-reset-code-maker:
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  only:
    - /^(master.*)$/
  stage:
    build-scripted-api-atoms
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/reset-code-maker"
    IMG_TAG: "latest"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/reset-code-maker-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/reset-code-maker-atom/."
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - ./ci-cd/ci/build-image.sh
#  needs:
#    - job: build-scripted-api-atoms-base