build-ssa-tag-pill-svg-generator:
  tags:
    - piximos
  stage:
    build-sa-bash
  variables:
    IMAGE_NAME: "scriptedatom/tag-pill-svg-generator"
    DOCKER_IMAGE_PATH: "./sa-bash/tag-pill-svg-generator-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-bash/tag-pill-svg-generator-atom/."
  script:
    - ./ci-cd/scripts/build-public-image.sh
  needs:
    - build-sa-fastapi

