build-saa-s3-file-unzipper:
  tags:
    - piximos
  stage:
    build-sa-fastapi
  variables:
    IMAGE_NAME: "scriptedatom/s3-unzipper"
    DOCKER_IMAGE_PATH: "./sa-fastapi/s3-file-unzipper-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-fastapi/s3-file-unzipper-atom/."
  script:
    - ./ci-cd/scripts/build-public-image.sh
  needs:
    - build-sa-fastapi

