clean-saa-qr-code-s3:
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  only:
    - merge_requests
#  rules:
#    - if: $CI_COMMIT_BRANCH =~ /^(develop.*)|(dev.*)$/
  stage:
    clean-dev-data
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/qr-code-generator-s3"
    IMG_TAG: "dev"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    REG_VERSION: 0.16.1
  before_script:
    - apk add --no-cache curl
    - curl --fail --show-error --location "https://github.com/genuinetools/reg/releases/download/v$REG_VERSION/reg-linux-amd64" --output /usr/local/bin/reg
    - echo "$REG_SHA256  /usr/local/bin/reg" | sha256sum -c -
    - chmod a+x /usr/local/bin/reg
  script:
    - /usr/local/bin/reg rm -d --auth-url $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD "${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMG_TAG}"

clean-saa-qr-code-fs:
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  only:
    - merge_requests
#  rules:
#    - if: $CI_COMMIT_BRANCH =~ /^(develop.*)|(dev.*)$/
  stage:
    clean-dev-data
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/qr-code-generator-fs"
    IMG_TAG: "dev"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    REG_VERSION: 0.16.1
  before_script:
    - apk add --no-cache curl
    - curl --fail --show-error --location "https://github.com/genuinetools/reg/releases/download/v$REG_VERSION/reg-linux-amd64" --output /usr/local/bin/reg
    - echo "$REG_SHA256  /usr/local/bin/reg" | sha256sum -c -
    - chmod a+x /usr/local/bin/reg
  script:
    - /usr/local/bin/reg rm -d --auth-url $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD "${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMG_TAG}"

clean-saa-reset-code-maker:
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  only:
    - merge_requests
#  rules:
#    - if: $CI_COMMIT_BRANCH =~ /^(develop.*)|(dev.*)$/
  stage:
    clean-dev-data
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/reset-code-maker"
    IMG_TAG: "dev"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    REG_VERSION: 0.16.1
  before_script:
    - apk add --no-cache curl
    - curl --fail --show-error --location "https://github.com/genuinetools/reg/releases/download/v$REG_VERSION/reg-linux-amd64" --output /usr/local/bin/reg
    - echo "$REG_SHA256  /usr/local/bin/reg" | sha256sum -c -
    - chmod a+x /usr/local/bin/reg
  script:
    - /usr/local/bin/reg rm -d --auth-url $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD "${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMG_TAG}"