build-dev-sta-s3-file-sync:
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  only:
    refs:
      - /^(develop.*)|(dev.*)$/
    changes:
      - scripted-task-atoms/scripted-task-atoms-base/*
      - scripted-task-atoms/s3-file-sync-atom/*
  stage:
    build-scripted-task-atoms
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-task-atoms/qr-code-generator-s3"
    IMG_TAG: $CI_COMMIT_REF_NAME
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-task-atoms/s3-file-sync-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-task-atoms/s3-file-sync-atom/."
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - ./ci-cd/scripts/build-image.sh
  needs:
    - build-dev-scripted-task-atoms-base

build-dev-sta-uptime-tracker:
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  only:
    refs:
      - /^(develop.*)|(dev.*)$/
    changes:
      - scripted-task-atoms/scripted-task-atoms-base/*
      - scripted-task-atoms/uptime-tracker-atom/*
  stage:
    build-scripted-task-atoms
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-task-atoms/uptime-tracker"
    IMG_TAG: $CI_COMMIT_REF_NAME
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-task-atoms/uptime-tracker-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-task-atoms/uptime-tracker-atom/."
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - ./ci-cd/scripts/build-image.sh
  needs:
    - build-dev-scripted-task-atoms-base
