build-ssa-pipeline-discorder:
  tags:
    - piximos
  stage:
    build-sa-bash
  variables:
    IMAGE_NAME: "scriptedatom/pipeline-discorder"
    DOCKER_IMAGE_PATH: "./sa-bash/pipeline-discorder-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-bash/pipeline-discorder-atom/."
  script:
    - ./ci-cd/scripts/build-public-image.sh
  needs:
    - build-sa-fastapi

