build-ssa-pipeline-discorder:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      when: on_success
    - if: $CI_COMMIT_REF_NAME =~ /^(ci|sa|ssa|saa|sta)\-?(\-.*)?$/
      when: on_success
      variables:
        SA_BETA_BUILD: "true"
  stage:
    build-sa-bash
  variables:
    IMAGE_NAME: "scriptedatom/ssa-pipeline-discorder"
    DOCKER_IMAGE_PATH: "./sa-bash/pipeline-discorder-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-bash/pipeline-discorder-atom/."
  script:
    - ./ci-cd/scripts/build-public-image.sh
  needs:
    - build-sa-fastapi

ssa-pipeline-discorder-post-flight:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(ci|sa|ssa|saa|sta)\-?(\-.*)?$/
      when: on_success
      variables:
        SA_BETA_BUILD: "true"
        SUCCESS: "true"
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      when: on_success
      variables:
        SUCCESS: "true"
    - if: $CI_COMMIT_REF_NAME =~ /^(ci|sa|ssa|saa|sta)\-?(\-.*)?$/
      when: on_failure
      variables:
        SA_BETA_BUILD: "true"
        SUCCESS: "false"
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      when: on_failure
      variables:
        SUCCESS: "false"
  variables:
    IMAGE: "scriptedatom/ssa-pipeline-discorder"
    TAGS: "latest"
  stage:
    post-flight
  needs:
    - build-ssa-pipeline-discorder
  script:
    - ./ci-cd/scripts/pipeline-after-build.sh
