build-saa-base:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      variables:
        SA_BASE_VERSION: ${saa_base_version}
        IMAGE_VERSION: ${saa_base_version}
  stage:
    build-scripted-api-atoms
  variables:
    IMAGE_NAME: "scriptedatom/saa-base"
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/scripted-api-atoms-base/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/scripted-api-atoms-base/."
  needs:
    - validate-branch-name
  script:
    - ./ci-cd/scripts/build-public-image.sh

saa-base-slacker:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      when: on_success
      variables:
        SUCCESS: "true"
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      when: on_failure
      variables:
        SUCCESS: "false"
  variables:
    SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
    IMAGE: "scriptedatom/saa-base"
    TAGS: "latest ${saa_base_version}"
  stage:
    broadcast
  needs:
    - validate-branch-name
  script:
    - ./ci-cd/scripts/pipeline-slacker.sh
