build-scripted-api-atoms-base:
  tags:
    - soyoustart1
  only:
    - /^(master)$/
  stage:
    build-bases
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms-base"
    BUILD_VERSION: "true"
    IMG_TAG: "latest"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/scripted-api-atoms-base/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/scripted-api-atoms-base/."
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./ci-cd/scripts/build-image.sh
  artifacts:
    paths:
      - ./output.txt
    expire_in: 7 days

build-scripted-task-atoms-base:
  tags:
    - soyoustart1
  only:
    - /^(master)$/
  stage:
    build-bases
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-task-atoms-base"
    BUILD_VERSION: "true"
    IMG_TAG: "latest"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-task-atoms/scripted-task-atoms-base/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-task-atoms/scripted-task-atoms-base/."
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./ci-cd/scripts/build-image.sh
  artifacts:
    paths:
      - ./output.txt
    expire_in: 7 days