build-sta-s3-file-sync:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(develop.*)|(dev.*)$/
      changes:
        - scripted-task-atoms/scripted-task-atoms-base/*
        - scripted-task-atoms/s3-file-sync-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      variables:
        PUBLIC_IMAGE_NAME: "piximos/scripted-task-atom-s3-file-sync"
  stage:
    build-scripted-task-atoms
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-task-atoms/qr-code-generator-s3"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-task-atoms/s3-file-sync-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-task-atoms/s3-file-sync-atom/."
  needs:
    - build-scripted-task-atoms-base
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./ci-cd/scripts/build-image.sh

build-sta-uptime-tracker:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(develop.*)|(dev.*)$/
      changes:
        - scripted-task-atoms/scripted-task-atoms-base/*
        - scripted-task-atoms/uptime-tracker-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      variables:
        PUBLIC_IMAGE_NAME: "piximos/scripted-task-atom-uptime-tracker"
  stage:
    build-scripted-task-atoms
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-task-atoms/uptime-tracker"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-task-atoms/uptime-tracker-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-task-atoms/uptime-tracker-atom/."
  needs:
    - build-scripted-task-atoms-base
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./ci-cd/scripts/build-image.sh

