build-saa-qr-code-s3:
  tags:
    - soyoustart1
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(develop.*)|(dev.*)$/
      changes:
        - scripted-api-atoms/scripted-api-atoms-base/*
        - scripted-api-atoms/qr-code-s3-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      variables:
        PUBLIC_IMAGE_NAME: "piximos/scripted-api-atom-qr-code-generator-s3"
  stage:
    build-scripted-api-atoms
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/qr-code-generator-s3"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/qr-code-s3-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/qr-code-s3-atom/."
  needs:
    - build-scripted-api-atoms-base
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./ci-cd/scripts/build-image.sh
  artifacts:
    paths:
      - ./output.txt
      - ./build-log.txt
    expire_in: 7 days

build-saa-qr-code-fs:
  tags:
    - soyoustart1
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(develop.*)|(dev.*)$/
      changes:
        - scripted-api-atoms/scripted-api-atoms-base/*
        - scripted-api-atoms/qr-code-fs-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      variables:
        PUBLIC_IMAGE_NAME: "piximos/scripted-api-atom-qr-code-generator-fs"
  stage:
    build-scripted-api-atoms
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/qr-code-generator-fs"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/qr-code-fs-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/qr-code-fs-atom/."
  needs:
    - build-scripted-api-atoms-base
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./ci-cd/scripts/build-image.sh
  artifacts:
    paths:
      - ./output.txt
      - ./build-log.txt
    expire_in: 7 days

build-saa-otp-maker:
  tags:
    - soyoustart1
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(develop.*)|(dev.*)$/
      changes:
        - scripted-api-atoms/scripted-api-atoms-base/*
        - scripted-api-atoms/otp-maker-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      variables:
        PUBLIC_IMAGE_NAME: "piximos/scripted-api-atom-otp-maker"
  stage:
    build-scripted-api-atoms
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/otp-maker"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/otp-maker-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/otp-maker-atom/."
  needs:
    - build-scripted-api-atoms-base
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./ci-cd/scripts/build-image.sh
  artifacts:
    paths:
      - ./output.txt
      - ./build-log.txt
    expire_in: 7 days

build-saa-s3-unzipper:
  tags:
    - soyoustart1
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(develop.*)|(dev.*)$/
      changes:
        - scripted-api-atoms/scripted-api-atoms-base/*
        - scripted-api-atoms/s3-file-unzipper-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
      variables:
        PUBLIC_IMAGE_NAME: "piximos/scripted-api-atom-s3-unzipper"
  stage:
    build-scripted-api-atoms
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/s3-unzipper"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/s3-file-unzipper-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/s3-file-unzipper-atom/."
  needs:
    - build-scripted-api-atoms-base
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./ci-cd/scripts/build-image.sh
  artifacts:
    paths:
      - ./output.txt
      - ./build-log.txt
    expire_in: 7 days
