build-saa-redis-subscriber:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
    - if: $CI_COMMIT_REF_NAME =~ /^(ci|sa|ssa|saa|sta)\-?(\-.*)?$/
      variables:
        SA_BETA_BUILD: "true"
  stage:
    build-sa-python
  variables:
    IMAGE_NAME: "scriptedatom/redis-subscriber"
    DOCKER_IMAGE_PATH: "./sa-python/redis-subscriber-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-python/redis-subscriber-atom/."
  script:
    - ./ci-cd/scripts/build-public-image.sh
  needs:
    - build-sa-python

