docker-mirror-saa-qr-code-s3:
  tags:
    - soyoustart1
  only:
    - /^(master)$/
  stage:
    mirror-scripted-api-atoms
  needs:
    - build-saa-qr-code-s3
  variables:
    IMAGE_NAME: "piximos/scripted-api-atom-qr-code-generator-s3"
    IMG_TAG: "latest"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/qr-code-s3-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/qr-code-s3-atom/."
  script:
    - echo "$DOCKER_REGISTRY_TOKEN" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin
    - ./ci-cd/scripts/build-public-image.sh

docker-mirror-saa-qr-code-fs:
  tags:
    - soyoustart1
  only:
    - /^(master)$/
  stage:
    mirror-scripted-api-atoms
  needs:
    - build-saa-qr-code-fs
  variables:
    IMAGE_NAME: "piximos/scripted-api-atom-qr-code-generator-fs"
    IMG_TAG: "latest"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/qr-code-fs-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/qr-code-fs-atom/."
  script:
    - echo "$DOCKER_REGISTRY_TOKEN" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin
    - ./ci-cd/scripts/build-public-image.sh

docker-mirror-saa-otp-maker:
  tags:
    - soyoustart1
  only:
    - /^(master)$/
  stage:
    mirror-scripted-api-atoms
  needs:
    - build-saa-otp-maker
  variables:
    IMAGE_NAME: "piximos/scripted-api-atom-otp-maker"
    IMG_TAG: "latest"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/otp-maker-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/otp-maker-atom/."
  script:
    - echo "$DOCKER_REGISTRY_TOKEN" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin
    - ./ci-cd/scripts/build-public-image.sh

docker-mirror-saa-s3-unzipper:
  tags:
    - soyoustart1
  only:
    - /^(master)$/
  stage:
    mirror-scripted-api-atoms
  needs:
    - build-saa-otp-maker
  variables:
    IMAGE_NAME: "piximos/scripted-api-atom-s3-unzipper"
    IMG_TAG: "latest"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/s3-file-unzipper-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/s3-file-unzipper-atom/."
  script:
    - echo "$DOCKER_REGISTRY_TOKEN" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin
    - ./ci-cd/scripts/build-public-image.sh
