build-ssa-harbor-image-cleaner:
  tags:
    - piximos
  stage:
    build-sa-bash
  variables:
    IMAGE_NAME: "scriptedatom/harbor-image-cleaner"
    DOCKER_IMAGE_PATH: "./sa-bash/harbor-image-cleaner-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-bash/harbor-image-cleaner-atom/."
  script:
    - ./ci-cd/scripts/build-public-image.sh
  needs:
    - build-sa-fastapi

