build-saa-qr-code-s3-arm:
  tags:
    - piximos-arm
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^((develop|dev).*)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "true"
        MIRROR: "false"
      changes:
        - scripted-api-atoms/scripted-api-atoms-base/*
        - scripted-api-atoms/qr-code-s3-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^((minor|major)\-release)|(master)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "false"
        MIRROR: "true"
        PUBLIC_IMAGE_NAME: "scriptedatom/saa-qr-code-generator-s3"
  stage:
    build-scripted-api-atoms
  variables:
    IMG_COMPLEMENTARY_TAG: "-arm"
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/qr-code-generator-s3"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/qr-code-s3-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/qr-code-s3-atom/."
  needs:
    - build-saa-base-arm
  script:
    - ./ci-cd/scripts/build-image.sh

build-saa-qr-code-fs-arm:
  tags:
    - piximos-arm
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^((develop|dev).*)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "true"
        MIRROR: "false"
      changes:
        - scripted-api-atoms/scripted-api-atoms-base/*
        - scripted-api-atoms/qr-code-fs-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^((minor|major)\-release)|(master)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "false"
        MIRROR: "true"
        PUBLIC_IMAGE_NAME: "scriptedatom/saa-qr-code-generator-fs"
  stage:
    build-scripted-api-atoms
  variables:
    IMG_COMPLEMENTARY_TAG: "-arm"
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/qr-code-generator-fs"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/qr-code-fs-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/qr-code-fs-atom/."
  needs:
    - build-saa-base-arm
  script:
    - ./ci-cd/scripts/build-image.sh

build-saa-otp-maker-arm:
  tags:
    - piximos-arm
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^((develop|dev).*)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "true"
        MIRROR: "false"
      changes:
        - scripted-api-atoms/scripted-api-atoms-base/*
        - scripted-api-atoms/otp-maker-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^((minor|major)\-release)|(master)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "false"
        MIRROR: "true"
        PUBLIC_IMAGE_NAME: "scriptedatom/saa-otp-maker"
  stage:
    build-scripted-api-atoms
  variables:
    IMG_COMPLEMENTARY_TAG: "-arm"
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/otp-maker"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/otp-maker-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/otp-maker-atom/."
  needs:
    - build-saa-base-arm
  script:
    - ./ci-cd/scripts/build-image.sh

build-saa-s3-unzipper-arm:
  tags:
    - piximos-arm
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^((develop|dev).*)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "true"
        MIRROR: "false"
      changes:
        - scripted-api-atoms/scripted-api-atoms-base/*
        - scripted-api-atoms/s3-file-unzipper-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^((minor|major)\-release)|(master)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "false"
        MIRROR: "true"
        PUBLIC_IMAGE_NAME: "scriptedatom/saa-s3-unzipper"
  stage:
    build-scripted-api-atoms
  variables:
    IMG_COMPLEMENTARY_TAG: "-arm"
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/s3-unzipper"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/s3-file-unzipper-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/s3-file-unzipper-atom/."
  needs:
    - build-saa-base-arm
  script:
    - ./ci-cd/scripts/build-image.sh

build-saa-thumbnail-generator-s3-arm:
  tags:
    - piximos-arm
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^((develop|dev).*)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "true"
        MIRROR: "false"
      changes:
        - scripted-api-atoms/scripted-api-atoms-base/*
        - scripted-api-atoms/thumbnail-generator-s3-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^((minor|major)\-release)|(master)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "false"
        MIRROR: "true"
        PUBLIC_IMAGE_NAME: "scriptedatom/saa-thumbnail-generator"
  stage:
    build-scripted-api-atoms
  variables:
    IMG_COMPLEMENTARY_TAG: "-arm"
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/thumbnail-generator"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/thumbnail-generator-s3-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/thumbnail-generator-s3-atom/."
  needs:
    - build-saa-base-arm
  script:
    - ./ci-cd/scripts/build-image.sh
