build-ssa-s3-file-backup-arm:
  tags:
    - piximos-arm
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^((develop|dev).*)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "true"
        MIRROR: "false"
      changes:
        - scripted-simple-atoms/scripted-simple-atoms-base/*
        - scripted-simple-atoms/s3-file-backup-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^((minor|major)\-release)|(master)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "false"
        MIRROR: "true"
        PUBLIC_IMAGE_NAME: "scriptedatom/ssa-s3-file-backup-atom"
  stage:
    build-scripted-simple-atoms
  variables:
    IMG_COMPLEMENTARY_TAG: "-arm"
    IMAGE_NAME: "piximos/scripted-atoms/scripted-simple-atoms/s3-file-backup-atom"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-simple-atoms/s3-file-backup-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-simple-atoms/s3-file-backup-atom/."
  needs:
    - build-ssa-base-arm
  script:
    - ./ci-cd/scripts/build-image.sh

build-ssa-git-tagger-arm:
  tags:
    - piximos-arm
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^((develop|dev).*)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "true"
        MIRROR: "false"
      changes:
        - scripted-simple-atoms/scripted-simple-atoms-base/*
        - scripted-simple-atoms/git-tagger-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^((minor|major)\-release)|(master)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "false"
        MIRROR: "true"
        PUBLIC_IMAGE_NAME: "scriptedatom/ssa-git-tagger-atom"
  stage:
    build-scripted-simple-atoms
  variables:
    IMG_COMPLEMENTARY_TAG: "-arm"
    IMAGE_NAME: "piximos/scripted-atoms/scripted-simple-atoms/git-tagger-atom"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-simple-atoms/git-tagger-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-simple-atoms/git-tagger-atom/."
  needs:
    - build-ssa-base-arm
  script:
    - ./ci-cd/scripts/build-image.sh

build-ssa-git-mirror-arm:
  tags:
    - piximos-arm
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^((develop|dev).*)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "true"
        MIRROR: "false"
      changes:
        - scripted-simple-atoms/scripted-simple-atoms-base/*
        - scripted-simple-atoms/git-mirror-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^((minor|major)\-release)|(master)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "false"
        MIRROR: "true"
        PUBLIC_IMAGE_NAME: "scriptedatom/ssa-git-mirror-atom"
  stage:
    build-scripted-simple-atoms
  variables:
    IMG_COMPLEMENTARY_TAG: "-arm"
    IMAGE_NAME: "piximos/scripted-atoms/scripted-simple-atoms/git-mirror-atom"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-simple-atoms/git-mirror-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-simple-atoms/git-mirror-atom/."
  needs:
    - build-ssa-base-arm
  script:
    - ./ci-cd/scripts/build-image.sh

build-ssa-pipeline-slacker-arm:
  tags:
    - piximos-arm
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^((develop|dev).*)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "true"
        MIRROR: "false"
      changes:
        - scripted-simple-atoms/scripted-simple-atoms-base/*
        - scripted-simple-atoms/pipeline-slacker-atom/*
    - if: $CI_COMMIT_REF_NAME =~ /^((minor|major)\-release)|(master)$/
      variables:
        BUILD_FOR_PRIVATE_REGISTRY: "false"
        MIRROR: "true"
        PUBLIC_IMAGE_NAME: "scriptedatom/ssa-pipeline-slacker-atom"
  stage:
    build-scripted-simple-atoms
  variables:
    IMG_COMPLEMENTARY_TAG: "-arm"
    IMAGE_NAME: "piximos/scripted-atoms/scripted-simple-atoms/pipeline-slacker-atom"
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-simple-atoms/pipeline-slacker-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-simple-atoms/pipeline-slacker-atom/."
  needs:
    - build-ssa-base-arm
  script:
    - ./ci-cd/scripts/build-image.sh