build-ssa-pipeline-slacker:
  tags:
    - piximos
  stage:
    build-sa-bash
  variables:
    IMAGE_NAME: "scriptedatom/pipeline-slacker"
    DOCKER_IMAGE_PATH: "./sa-bash/pipeline-slacker-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-bash/pipeline-slacker-atom/."
  script:
    - ./ci-cd/scripts/build-public-image.sh
  needs:
    - build-sa-fastapi

