build-ssa-s3-file-backup:
  tags:
    - piximos
  stage:
    build-sa-s3
  variables:
    IMAGE_NAME: "scriptedatom/sa-s3-file-backup"
    DOCKER_IMAGE_PATH: "./sa-s3/s3-file-backup-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-s3/s3-file-backup-atom/."
  script:
    - ./ci-cd/scripts/build-public-image.sh
  needs:
    - build-sa-fastapi

