build-dev-scripted-api-atoms-base:
  tags:
    - soyoustart1
  only:
    refs:
      - /^(develop.*)|(dev.*)$/
    changes:
      - scripted-api-atoms/scripted-api-atoms-base/*
      - scripted-api-atoms/qr-code-s3-atom/*
      - scripted-api-atoms/qr-code-fs-atom/*
      - scripted-api-atoms/otp-maker-atom/*
      - scripted-api-atoms/s3-file-unzipper-atom/*
  stage:
    build-bases
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms-base"
    IMG_TAG: $CI_COMMIT_REF_NAME
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/scripted-api-atoms-base/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/scripted-api-atoms-base/."
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - ./ci-cd/scripts/build-image.sh

build-dev-scripted-task-atoms-base:
  tags:
    - soyoustart1
  only:
    refs:
      - /^(develop.*)|(dev.*)$/
    changes:
      - scripted-task-atoms/scripted-task-atoms-base/*
      - scripted-task-atoms/s3-file-sync-atom/*
  stage:
    build-bases
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-task-atoms-base"
    IMG_TAG: $CI_COMMIT_REF_NAME
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-task-atoms/scripted-task-atoms-base/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-task-atoms/scripted-task-atoms-base/."
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - ./ci-cd/scripts/build-image.sh