build-dev-saa-qr-code-s3:
  tags:
    - soyoustart1
  only:
    refs:
      - /^(develop.*)|(dev.*)$/
    changes:
      - scripted-api-atoms/scripted-api-atoms-base/*
      - scripted-api-atoms/qr-code-s3-atom/*
  stage:
    build-scripted-api-atoms
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/qr-code-generator-s3"
    IMG_TAG: $CI_COMMIT_REF_NAME
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/qr-code-s3-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/qr-code-s3-atom/."
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - ./ci-cd/scripts/build-image.sh
  needs:
    - build-dev-scripted-api-atoms-base


build-dev-saa-qr-code-fs:
  tags:
    - soyoustart1
  only:
    refs:
      - /^(develop.*)|(dev.*)$/
    changes:
      - scripted-api-atoms/scripted-api-atoms-base/*
      - scripted-api-atoms/qr-code-fs-atom/*
  stage:
    build-scripted-api-atoms
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/qr-code-generator-fs"
    IMG_TAG: $CI_COMMIT_REF_NAME
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/qr-code-fs-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/qr-code-fs-atom/."
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - ./ci-cd/scripts/build-image.sh
  needs:
    - build-dev-scripted-api-atoms-base

build-dev-saa-otp-maker:
  tags:
    - soyoustart1
  only:
    refs:
      - /^(develop.*)|(dev.*)$/
    changes:
      - scripted-api-atoms/scripted-api-atoms-base/*
      - scripted-api-atoms/otp-maker-atom/*
  stage:
    build-scripted-api-atoms
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/otp-maker"
    IMG_TAG: $CI_COMMIT_REF_NAME
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/otp-maker-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/otp-maker-atom/."
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - ./ci-cd/scripts/build-image.sh
  needs:
    - build-dev-scripted-api-atoms-base

build-dev-saa-s3-unzipper:
  tags:
    - soyoustart1
  only:
    refs:
      - /^(develop.*)|(dev.*)$/
    changes:
      - scripted-api-atoms/scripted-api-atoms-base/*
      - scripted-api-atoms/s3-file-unzipper-atom/*
  stage:
    build-scripted-api-atoms
  variables:
    IMAGE_NAME: "piximos/scripted-atoms/scripted-api-atoms/s3-unzipper"
    IMG_TAG: $CI_COMMIT_REF_NAME
    DOCKER_REGISTRY: ${CI_REGISTRY}
    DOCKER_IMAGE_PATH: "./scripted-api-atoms/s3-file-unzipper-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./scripted-api-atoms/s3-file-unzipper-atom/."
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - ./ci-cd/scripts/build-image.sh
  needs:
    - build-dev-scripted-api-atoms-base
