build-saa-otp-maker:
  tags:
    - piximos
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /^(master)$/
    - if: $CI_COMMIT_REF_NAME =~ /^(ci|sa|ssa|saa|sta)\-?(\-.*)?$/
      variables:
        SA_BETA_BUILD: "true"
  stage:
    build-sa-fastapi
  variables:
    IMAGE_NAME: "scriptedatom/otp-maker"
    DOCKER_IMAGE_PATH: "./sa-fastapi/otp-maker-atom/Dockerfile"
    DOCKER_BUILD_CONTEXT: "./sa-fastapi/otp-maker-atom/."
  script:
    - ./ci-cd/scripts/build-public-image.sh
  needs:
    - build-sa-fastapi

